export const PROJECT_ADD = 'PROJECT_ADD'
export const PROJECT_SET_ALL = 'PROJECT_SET_ALL'
export const PROJECT_PERIOD_START = 'PROJECT_PERIOD_START'
export const PROJECT_PERIOD_STOP = 'PROJECT_PERIOD_STOP'
